service: sls-lambda-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  iamRoleStatements: # IAM Role Permissions
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
  environment:
    MONGODB_URI: ${self:custom.secrets.MONGODB_URI}
    MONGODB_DATABASE: ${self:custom.secrets.MONGODB_DATABASE}-dev
   

# Custom variables
custom:
  secrets: ${file(.secrets.json)}

# Plugins
plugins:
  - serverless-offline

# Functions
functions:
  sls-lambda-api:
    name: ${self:service}-${self:provider.stage}-sls-lambda-api
    handler: handler.router
    layers:
      - arn:aws:lambda:us-east-1:${self:custom.secrets.AWS_ACC}:layer:mongoDB:1
    timeout: 30
    events:
      - http:
          path: 'v1/{proxy+}'
          method: any
  sls-get-context:
    name: ${self:service}-${self:provider.stage}-sls-get-context
    handler: context.handler
    timeout: 30
    events:
      - http:
          path: 'v1/version'
          method: GET
