name: Deploy Project

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deploy Stage Name"
        default: dev
        required: true
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Create Secrets File
      uses: schdck/create-env-json@v1
      id: create-env
      with:
        file-name: '.secrets.json'
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        NODE_ENV: ${{ github.event.inputs.stage }}
    - run: echo ${{ steps.create-env.outputs.full-path }}
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy -s ${{ github.event.inputs.stage }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
