name: Test

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deploy Stage Name"
        default: dev
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Create credentials JSON
      run: |
        echo '{ "MONGODB_URI": "${{ secrets.MONGODB_URI }}", "MONGODB_DATABASE":"pinch","NODE_ENV":"${{ github.event.inputs.stage }}"}' > .secrets.json
        
    - name: Deploy with Serverless
      run: |
        npm install -g serverless
        serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        serverless deploy
